version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - oresight-net
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - oresight-net
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data:z
    networks:
      - oresight-net
  frontend:
    build:
      context: ./oresight-fe
    image: ${DOCKER_HUB_REPO}/oresight-fe:${DOCKER_TAG}
    container_name: frontend
    environment:
      - ENV=dev
    ports:
      - "3000:3000"
    networks:
      - oresight-net
  backend:
    build:
      context: .
    image: ${DOCKER_HUB_REPO}/oresight-be:${DOCKER_TAG}
    container_name: backend
    environment:
      - ENV=dev
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432
    ports:
      - "8000:8000"
    networks:
      - oresight-net
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - selenium
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - oresight-net
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: '2gb'
    ports:
      - "4444:4444"
    networks:
      - oresight-net
networks:
  oresight-net:
    driver: bridge