version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - oresight-net
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - oresight-net
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data:z
    networks:
      - oresight-net
  oresight-fe:
    build:
      context: ./frontend
    image: ${DOCKER_HUB_REPO}/oresight-fe:${DOCKER_TAG}
    environment:
      - ENV=dev
    networks:
      - oresight-net
  oresight-be:
    build:
      context: .
    image: ${DOCKER_HUB_REPO}/oresight-be:${DOCKER_TAG}
    environment:
      - ENV=dev
    networks:
      - oresight-net
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - oresight-net
networks:
  oresight-net:
    driver: bridge