""" Library of all the prompts used by the app. """
from langchain.prompts import PromptTemplate

BIO_EXTRACTION_PROMPT_TMPL = PromptTemplate.from_template(
    "Given the following text, extract the information of all the people mentioned in the text.\n"
    "\n"
    "\n"
    "Text: {text}\n"
    "\n"
    "\n"
    "Extract in the following json schema format:\n"
    "\n"
    "\n"
    "```json\n"
    "{{\n"
    "  \"people\": [\n"
    "    {{\n"
    "      \"name\": \"John Doe\",\n"
    "      \"title\": \"CEO\",\n"
    "      \"bio\": \"John Doe is the CEO of ABC. He has been working in the field of AI for 20 years\",\n"
    "\"interests\": \"John J. Gilluly III has a diverse range of areas of interest in the legal sector. These include "
    "Corporate law, Emerging Growth and Venture Capital, Energy and Natural Resources, Equity Capital Markets, "
    "Financial Services, Healthcare, Life Sciences, Mergers and Acquisitions, Private Equity, and Technology. "
    "Additionally, he is also invested in Environmental, Social, and Governance (ESG) matters.\",\n"
    "      \"contact\": \"+1-908-123-1234\",\n"
    "      \"email\": \"a@a.com\"\n"
    "    }},\n"
    "    {{\n"
    "      \"name\": \"Jane Doe\",\n"
    "      \"title\": \"CTO\",\n"
    "      \"bio\": \"Jane Doe is the CTO of ABC. She has been working in the field of AI for 20 years.\"\n"
    "      \"contact\": \"+1-908-123-1234\",\n"
    "\"interests\": \"John J. Gilluly III has a diverse range of areas of interest in the legal sector. These include "
    "Corporate law, Emerging Growth and Venture Capital, Energy and Natural Resources, Equity Capital Markets, "
    "Financial Services, Healthcare, Life Sciences, Mergers and Acquisitions, Private Equity, and Technology. "
    "Additionally, he is also invested in Environmental, Social, and Governance (ESG) matters.\",\n"
    "      \"email\": \"b@b.com\"\n"
    "    }}\n"
    "  ]\n"
    "}}\n"
    "```\n"
    "\n"
)

